In [2]:
# Pandas Basics
# Data Cleaning and Preprocessing
import pandas as pd
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)
print(type(series))

data = {'a':1, 'b':2, 'c':3}
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64

In [3]:
data=[1,2,3,4,5]
index=['a','b','c','d','e']
pd.Series(data,index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
# DataFrame
data = {
        'Name': ['Alice', 'Bob', 'Charlie'], 
        'Age': [25, 30, 35], 
        'City': ['New York', 'London', 'Paris'], 
        'Country': ['USA', 'UK', 'France'], 
        'Salary': [50000, 60000, 70000]
    }

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age      City Country  Salary
0    Alice   25  New York     USA   50000
1      Bob   30    London      UK   60000
2  Charlie   35     Paris  France   70000
<class 'pandas.core.frame.DataFrame'>

In [5]:
## Create a Dataframe from the List of Dictionaries

data = [
        {'Name': 'Alice', 'Age': 25, 'City': 'New York', 'Country': 'USA', 'Salary': 50000},
        {'Name': 'Bob', 'Age': 30, 'City': 'London', 'Country': 'UK', 'Salary': 60000},
        {'Name': 'Charlie', 'Age': 35, 'City': 'Paris', 'Country': 'France', 'Salary': 70000}
    ]

df = pd.DataFrame(data)
print(df)

      Name  Age      City Country  Salary
0    Alice   25  New York     USA   50000
1      Bob   30    London      UK   60000
2  Charlie   35     Paris  France   70000

In [6]:
df=pd.read_csv('data\\customers-100.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [7]:
df['Customer Id'].head(5)

0    DD37Cf93aecA6Dc
1    1Ef7b82A4CAAD10
2    6F94879bDAfE5a6
3    5Cef8BFA16c5e3c
4    053d585Ab6b3159
Name: Customer Id, dtype: object

In [8]:
df.loc[0].head(5)

Index                        1
Customer Id    DD37Cf93aecA6Dc
First Name              Sheryl
Last Name               Baxter
Company        Rasmussen Group
Name: 0, dtype: object

In [9]:
df.iloc[0].head(5)

Index                        1
Customer Id    DD37Cf93aecA6Dc
First Name              Sheryl
Last Name               Baxter
Company        Rasmussen Group
Name: 0, dtype: object

In [10]:
df.at[3,'Customer Id']

'5Cef8BFA16c5e3c'

In [11]:
# df.iat(3,4)

In [12]:
# Data manipulation with data frames
# df['Ravi']=[1,2,3,4,5]

In [13]:
# df.drop('Company',axis=1,inplace=True)
# df.drop('City',axis=1,inplace=True)

In [14]:
df.describe()

          Index
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

In [15]:
df=pd.read_csv('data\\customers-100.csv')
df.head(5)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [16]:
df.describe()
print(type(df))

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [17]:
# Fill with Mean of the column
df.dtypes
df['Index']=df['Index'].fillna(df['Index'].mean())
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/

In [18]:
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object

In [19]:
# column Renaming
df.rename(columns={'Index':'S.No'})
# Change Data type

df['S.No']=df['Index'].astype('int')
df.dtypes

Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
S.No                  int64
dtype: object

In [22]:
# Data Aggregation and Grouping

df
# df.groupby('Country')

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website,S.No
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/,1
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/,2
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/,3
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/,4
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/,5
5,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/,6
6,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/,7
7,8,0e04AFde9f225dE,Brett,Mullen,"Sanford, Davenport and Giles",Kimport,Bulgaria,001-583-352-7197x297,001-333-145-0369,asnow@colon.com,2021-04-12,https://hammond-ramsey.com/,8
8,9,C2dE4dEEc489ae0,Sheryl,Meyers,Browning-Simon,Robersonstad,Cyprus,854-138-4911x5772,+1-448-910-2276x729,mariokhan@ryan-pope.org,2020-01-13,https://www.bullock.net/,9
9,10,8C2811a503C7c5a,Michelle,Gallagher,Beck-Hendrix,Elaineberg,Timor-Leste,739.218.2516x459,001-054-401-0347x617,mdyer@escobar.net,2021-11-08,https://arias.com/,10

In [28]:
df.groupby('Country')['Subscription Date'].count()

Country
Antigua and Barbuda           1
Bosnia and Herzegovina        1
Bulgaria                      1
Chile                         1
Cyprus                        1
Djibouti                      1
Dominican Republic            1
Pitcairn Islands              1
Slovakia (Slovak Republic)    1
Timor-Leste                   1
Name: Subscription Date, dtype: int64

In [30]:
csv_file = 'data\\sales_data_sample.csv'
sales_df = pd.read_csv(csv_file)
sales_df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [35]:
groupped_sales = sales_df.groupby('COUNTRY')['SALES']
groupped_sales.sum()

COUNTRY
Australia       630623.10
Austria         202062.53
Belgium         108412.62
Canada          224078.56
Denmark         245637.15
Finland         329581.91
France         1110916.52
Germany         220472.09
Ireland          57756.43
Italy           374674.31
Japan           188167.81
Norway          307463.70
Philippines      94015.73
Singapore       288488.41
Spain          1215686.92
Sweden          210014.21
Switzerland     117713.56
UK              478880.46
USA            3627982.83
Name: SALES, dtype: float64

In [34]:
groupped_sales.mean()

COUNTRY
Australia      3408.773514
Austria        3673.864182
Belgium        3285.230909
Canada         3201.122286
Denmark        3899.002381
Finland        3582.412065
France         3537.950701
Germany        3556.001452
Ireland        3609.776875
Italy          3315.701858
Japan          3618.611731
Norway         3617.220000
Philippines    3615.989615
Singapore      3651.752025
Spain          3554.640117
Sweden         3684.459825
Switzerland    3797.211613
UK             3325.558750
USA            3613.528715
Name: SALES, dtype: float64

In [38]:
groupped_sales = sales_df.groupby('COUNTRY')['SALES'].agg(['sum','mean', 'max', 'min'])
groupped_sales

                    sum         mean       max      min
COUNTRY
Australia     630623.10  3408.773514   9774.03   652.35
Austria       202062.53  3673.864182   9240.00   640.05
Belgium       108412.62  3285.230909   6804.63   881.40
Canada        224078.56  3201.122286   9064.89  1119.93
Denmark       245637.15  3899.002381  10468.90  1146.50
Finland       329581.91  3582.412065  10606.20   891.03
France       1110916.52  3537.950701  11739.70   482.13
Germany       220472.09  3556.001452   8940.96   948.99
Ireland        57756.43  3609.776875   8258.00  1056.40
Italy         374674.31  3315.701858   9160.36   577.60
Japan         188167.81  3618.611731  10758.00   553.95
Norway        307463.70  3617.220000   8844.12  1129.04
Philippines    94015.73  3615.989615   7483.98  1173.15
Singapore     288488.41  3651.752025  10993.50   785.64
Spain        1215686.92  3554.640117  12001.00   683.80
Sweden        210014.21  3684.459825   7209.11  1467.48
Switzerland   117713.56  3797.211613   6761.60  1205.04
UK            478880.46  3325.558750  11886.60   710.20
USA          3627982.83  3613.528715  14082.80   541.14

In [44]:
### Merging and Joining DataFrames

df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})

df2 = pd.DataFrame({
    'ID': [2, 3, 4],
    'City': ['New York', 'London', 'Paris'],
    'Country': ['USA', 'UK', 'France']
})

merged_df = pd.merge(df1, df2, on='ID', how='outer')
print(merged_df)

   ID     Name   Age      City Country
0   1    Alice  25.0       NaN     NaN
1   2      Bob  30.0  New York     USA
2   3  Charlie  35.0    London      UK
3   4      NaN   NaN     Paris  France

In [53]:
import pandas as pd
from io import StringIO
# Read From Json

json_file = '{ "Name": ["Alice", "Bob", "Charlie"], "Age": [25, 30, 35], "City": ["New York", "London", "Paris"], "Country": ["USA", "UK", "France"], "Salary": [50000, 60000, 70000] }'
df = pd.read_json(StringIO(json_file))
df.head(5)
df.to_json('data\\output.json', orient='records')
df.to_csv('data\\output.csv', index=False)

In [70]:
%pip install html5lib  lxml openpyxl

Requirement already satisfied: html5lib in c:\users\ravi7\appdata\local\programs\python\python313\lib\site-packages (1.1)
Requirement already satisfied: lxml in c:\users\ravi7\appdata\local\programs\python\python313\lib\site-packages (6.1.0)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: six>=1.9 in c:\users\ravi7\appdata\local\programs\python\python313\lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\ravi7\appdata\local\programs\python\python313\lib\site-packages (from html5lib) (0.5.1)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
url = 'https://www.fdic.gov/bank-failures/failed-bank-list'
df=pd.read_html(url)
df[0].head(5)

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546

In [75]:
excel_file = 'data\\esales.xlsx'
df = pd.read_excel(excel_file)
df.head(5)

   Postcode  Sales_Rep_ID Sales_Rep_Name  Year         Value
0      2121           456           Jane  2011  84219.497311
1      2092           789         Ashish  2012  28322.192268
2      2128           456           Jane  2013  81878.997241
3      2073           123           John  2011  44491.142121
4      2134           789         Ashish  2012  71837.720959

In [ ]:
# df.to_pickle('data\\esales.pkl')

In [ ]:
# df.read_pickle('data\\esales.pkl')

AttributeError: 'DataFrame' object has no attribute 'read_pickle'